### ISSUE TITLE
Support JSON as config value

### ISSUE THREAD

**Issue by akshayrawat** [blimmer/ember-cli-server-variables#15]
It should be nice if a config whose value is a JSON would be returned as a JSON, instead of a String which then needs to be parsed as a JSON.

**Comment by akshayrawat** [comment]
Yep, that's perfect.

**Comment by blimmer** [comment]
I published 2.0 with this change. Because it could cause problems for folks who were parsing the JSON themselves, this could break their apps, hence the major version bump.
