### ISSUE TITLE
Ember Meta SEO Solution?

### ISSUE THREAD

**Issue by e-karma** [blimmer/ember-cli-server-variables#5]
Can this be used for Dynamic Meta-Description per page Tags? I'm looking for something that can apply dynamic Page Titles + Meta-Description Tags.

**Comment by blimmer** [comment]
I don't think that this project is quite what you're looking for as far as modifying the `head` tag while the app is running. My intention was to keep this add-on simply for server-written, client-read tags.

However, I do know of a few other add-ons that might be close to what you want. First, for page title, I use [ember-cli-document-title](https://github.com/kimroen/ember-cli-document-title). I also have a homegrown solution for modifying `meta` tags. You can find the source [here](https://gist.github.com/blimmer/005ba2850be52443ea0c). The meta modifications seems like a common problem and was [mentioned recently](https://github.com/kimroen/ember-cli-document-title/issues/4) in the ember-cli-document-title issue tracker. Perhaps you could ping the requester ( @t4t5 ) and maybe start a project?

**Comment by e-karma** [comment]
haha yea, that's me mentioning the same problem on that link. I'm a bit on
the JR. side to build it out myself & am stuck in limbo trying to get SEO
started before fastboot solves stuff like this.

i'll try out your homegrown solution & thanks for the help!

**Comment by blimmer** [comment]
No problem.

We're using prerender.io and that RouteMetaMixin (from the gist) and it's working just fine for us. Because this request is outside the scope of this add-on, I'm going to close this issue. I'll also keep in mind that lots of people need to modify meta tags for SEO and add it to my list of potential OSS projects.

It seems like this is so common that maybe you should even [write an RFC](https://github.com/emberjs/rfcs) to have this sort of thing integrated into Ember...

**Comment by Saurav-gaur** [comment]
Hi Blimmer,

Can you help me to carryout SEO in Ember Application using Prerender.IO

**Comment by blimmer** [comment]
@Saurav-gaur check out their documentation https://prerender.io/documentation

**Comment by Saurav-gaur** [comment]
Thank you Ben Limmer ...

**Comment by Saurav-gaur** [comment]
@blimmer , I have used that But I'm getting an issue ...



phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.


phantom stdout:   phantomjs://code/shim.js:1815 in send
  phantomjs://code/shim.js:1815 in _start
  phantomjs://code/shim.js:1842


Environment ( We are using):
Ember Version:  2.5
Phantom Version: 2.1.1 
Node Version: 4.4.0


What is the possible issue?

**Comment by blimmer** [comment]
I'm not sure - I would recommend reaching out to prerender customer support. I am not affiliated with prerender.io in any way.

**Comment by Saurav-gaur** [comment]
Thanks Ben
